image:
  file: .gitpod/Dockerfile
  context: .
ports:
- port: 80
- port: 8000
tasks:
- init: >
    composer install --ignore-platform-reqs &&
    cp .env.gitpod .env &&
    .gitpod/start-db.sh && .gitpod/init-db.sh &&
    composer migrate
  command: .gitpod/start-db.sh
