language: php
php:
  - "5.4"
services:
  - mysql
env:
  - KOHANA_ENV=testing
before_script:
  - composer install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive
  - mkdir application/cache application/logs
  - chmod 777 application/cache application/logs
  - cp application/tests/behat.template application/tests/behat.yml
  # db setup
  - mysql -e 'create database lamu_test;'
  - ./minion --task=migrations:run --up
  # webserver setup
  - php -S localhost:8000 httpdocs/index.php &
  - sleep 3
script:
  - ./bin/behat --config application/tests/behat.yml
  - ./bin/phpunit -c application/tests/phpunit.xml
